import React, { useState } from 'react';
import { ActivityIndicator, Pressable, View, useWindowDimensions } from 'react-native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, Chip, Field, fonts, Icon, IconButton, Sheet, Txt } from './UI';
import { useApp } from '../lib/store';
import DiscoverScreen from '../screens/DiscoverScreen';
import SavedScreen from '../screens/SavedScreen';
import ListingsScreen from '../screens/ListingsScreen';
import MessagesScreen from '../screens/MessagesScreen';
import AccountScreen from '../screens/AccountScreen';

const Tab = createBottomTabNavigator();
const navItems = [
  { name: 'Discover', icon: 'compass-outline', active: 'compass' },
  { name: 'Saved cars', icon: 'heart-outline', active: 'heart' },
  { name: 'Messages', icon: 'chatbubble-ellipses-outline', active: 'chatbubble-ellipses' },
  { name: 'My listings', icon: 'car-sport-outline', active: 'car-sport' },
];
export function Logo({ small = false }: { small?: boolean }) { const { theme } = useApp(); return <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><View style={{ width: small ? 28 : 32, height: small ? 28 : 32, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 3, transform: [{ skewX: '-15deg' }] }}><View style={{ width: 9, height: 20, backgroundColor: theme.forest, borderRadius: 3 }} /><View style={{ width: 9, height: 28, backgroundColor: '#A7CF62', borderRadius: 3 }} /></View><Txt style={{ fontFamily: fonts.bold, fontSize: small ? 27 : 32, letterSpacing: -1.8 }}>drivn<Txt style={{ fontFamily: fonts.bold, fontSize: small ? 28 : 34, color: '#92B755' }}>.</Txt></Txt></View>; }
export default function AppShell({ navigation }: any) {
  const { width } = useWindowDimensions(); const desktop = width >= 1000;
  const { theme, saved, name, location, setLocation, conversations, ready, notify, toast } = useApp();
  const [active, setActive] = useState('Discover');
  const [sheet, setSheet] = useState('');
  const [customLocation, setCustomLocation] = useState('');
  const [support, setSupport] = useState('');
  const unread = conversations.filter(c => c.unread).length;
  const go = (screen: string) => { navigation.navigate('Main', { screen }); setActive(screen); };
  const initials = name.split(' ').slice(0, 2).map(x => x[0]).join('');
  return <SafeAreaView edges={['top', 'left', 'right']} style={{ flex: 1, backgroundColor: theme.surface }}><View style={{ flex: 1, flexDirection: 'row' }}>
    {desktop && <View style={{ width: 218, backgroundColor: theme.surface, borderRightWidth: 1, borderRightColor: theme.border, paddingHorizontal: 18, paddingTop: 26 }}>
      <Pressable onPress={() => go('Discover')} style={{ marginLeft: 12, marginBottom: 42 }}><Logo /></Pressable>
      <Txt style={{ fontSize: 9, color: theme.subtle, letterSpacing: 1.8, fontFamily: fonts.semibold, marginLeft: 16, marginBottom: 14 }}>YOUR NEXT CHAPTER</Txt>
      <View style={{ gap: 7 }}>{navItems.map(item => <Pressable key={item.name} onPress={() => go(item.name)} style={({ hovered }: any) => ({ flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 15, height: 47, borderRadius: 9, backgroundColor: active === item.name ? theme.tint : hovered ? theme.soft : 'transparent' })}><Icon name={active === item.name ? item.active : item.icon} size={19} color={active === item.name ? theme.forest : theme.muted} /><Txt style={{ fontFamily: active === item.name ? fonts.bold : fonts.medium, fontSize: 12, flex: 1, color: active === item.name ? theme.text : theme.muted }}>{item.name}</Txt>{item.name === 'Saved cars' && saved.length > 0 && <View style={{ backgroundColor: theme.soft, borderRadius: 5, paddingHorizontal: 6, paddingVertical: 3 }}><Txt style={{ color: theme.muted, fontSize: 9 }}>{saved.length}</Txt></View>}{item.name === 'Messages' && unread > 0 && <View style={{ width: 18, height: 18, borderRadius: 6, backgroundColor: '#D4F580', alignItems: 'center', justifyContent: 'center' }}><Txt style={{ color: '#3A4E25', fontSize: 9, fontFamily: fonts.bold }}>{unread}</Txt></View>}</Pressable>)}</View>
      <View style={{ height: 1, backgroundColor: theme.border, marginVertical: 24, marginHorizontal: 12 }} />
      <Pressable onPress={() => navigation.navigate('SellCar')} style={({ hovered }: any) => ({ flexDirection: 'row', gap: 12, alignItems: 'center', paddingHorizontal: 15, height: 43, borderRadius: 9, backgroundColor: hovered ? theme.soft : 'transparent' })}><Icon name="add-circle-outline" size={20} color={theme.forest} /><Txt style={{ fontFamily: fonts.semibold, fontSize: 12 }}>Sell your car</Txt><Icon name="arrow-up-outline" size={14} style={{ transform: [{ rotate: '45deg' }], marginLeft: 'auto' }} color={theme.muted} /></Pressable>
      <View style={{ flex: 1, minHeight: 38 }} />
      <View style={{ backgroundColor: theme.soft, borderRadius: 12, padding: 16, marginBottom: 20, overflow: 'hidden' }}><View style={{ width: 30, height: 30, borderRadius: 9, backgroundColor: theme.surface, alignItems: 'center', justifyContent: 'center', marginBottom: 11 }}><Icon name="sparkles-outline" size={17} color={theme.forest} /></View><Txt style={{ fontFamily: fonts.bold, fontSize: 12 }}>A little help goes a long way.</Txt><Txt style={{ color: theme.muted, fontSize: 10, lineHeight: 17, marginTop: 6 }}>From first search to first drive.{'\n'}We’re here for you.</Txt><Pressable onPress={() => setSheet('help')} style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 15 }}><Txt style={{ fontFamily: fonts.semibold, fontSize: 10 }}>Let’s talk</Txt><Icon name="arrow-forward" size={13} /></Pressable></View>
      <Pressable onPress={() => go('Account')} style={{ flexDirection: 'row', alignItems: 'center', gap: 11, paddingTop: 20, paddingBottom: 25, borderTopWidth: 1, borderColor: theme.border }}><View style={{ width: 36, height: 36, backgroundColor: '#EEECE3', borderRadius: 20, alignItems: 'center', justifyContent: 'center' }}><Txt style={{ fontFamily: fonts.semibold, fontSize: 11, color: '#716950' }}>{initials}</Txt></View><View style={{ flex: 1 }}><Txt style={{ fontFamily: fonts.semibold, fontSize: 11 }}>{name}</Txt><Txt style={{ color: theme.muted, fontSize: 9, marginTop: 3 }}>Your personal pit stop</Txt></View><Icon name="chevron-down" size={12} color={theme.muted} /></Pressable>
    </View>}
    <View style={{ flex: 1, minWidth: 0 }}>
      <View style={{ height: desktop ? 72 : 68, backgroundColor: theme.surface, borderBottomWidth: 1, borderBottomColor: theme.border, flexDirection: 'row', alignItems: 'center', paddingHorizontal: desktop ? 33 : 20, gap: 18 }}>
        {desktop ? <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}><Icon name="grid-outline" size={14} color={theme.muted} /><Txt style={{ fontSize: 11, color: theme.muted }}>Marketplace</Txt><Txt style={{ fontSize: 12, color: theme.subtle }}>/</Txt><Txt style={{ fontSize: 11, fontFamily: fonts.medium }}>{active}</Txt></View> : <Pressable onPress={() => go('Discover')}><Logo small /></Pressable>}
        <View style={{ flex: 1 }} />
        <Pressable onPress={() => { setCustomLocation(location); setSheet('location'); }} style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}><Icon name="location-outline" size={15} color={theme.muted} />{width > 500 && <Txt style={{ fontSize: 10, fontFamily: fonts.medium }}>{location}</Txt>}<Icon name="chevron-down" size={10} color={theme.muted} /></Pressable>
        <View style={{ height: 23, width: 1, backgroundColor: theme.border }} />
        <Pressable accessibilityLabel="Notifications" onPress={() => setSheet('notifications')} style={{ padding: 3 }}><Icon name="notifications-outline" size={20} /><View style={{ position: 'absolute', right: 3, top: 2, width: 6, height: 6, borderRadius: 4, backgroundColor: '#A3C963', borderWidth: 1, borderColor: theme.surface }} /></Pressable>
        <Pressable accessibilityLabel="Your profile" onPress={() => go('Account')} style={{ width: 32, height: 32, borderRadius: 18, backgroundColor: '#EDE9DC', alignItems: 'center', justifyContent: 'center' }}><Txt style={{ fontSize: 10, color: '#786E51', fontFamily: fonts.bold }}>{initials}</Txt></Pressable>
      </View>
      {!ready ? <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.bg }}><ActivityIndicator color={theme.forest} /><Txt style={{ marginTop: 15, color: theme.muted }}>Getting your next chapter ready…</Txt></View> : <Tab.Navigator initialRouteName="Discover" screenListeners={{ state: e => { const s = e.data.state; if (s) setActive(s.routes[s.index].name); } }} screenOptions={({ route }) => ({ headerShown: false, animation: 'fade', sceneStyle: { backgroundColor: theme.bg }, tabBarStyle: desktop ? { display: 'none' } : { backgroundColor: theme.surface, borderTopColor: theme.border, height: 72, paddingTop: 7, paddingBottom: 12, elevation: 0 }, tabBarActiveTintColor: theme.forest, tabBarInactiveTintColor: theme.muted, tabBarLabelStyle: { fontFamily: fonts.medium, fontSize: 9, lineHeight: 14, marginTop: 0 }, tabBarIcon: ({ focused, color }) => <Icon name={route.name === 'Account' ? (focused ? 'person' : 'person-outline') : navItems.find(i => i.name === route.name)?.[focused ? 'active' : 'icon']} color={color} size={21} /> })}>
        <Tab.Screen name="Discover" component={DiscoverScreen} />
        <Tab.Screen name="Saved cars" component={SavedScreen} />
        <Tab.Screen name="Messages" component={MessagesScreen} options={{ tabBarBadge: unread || undefined, tabBarBadgeStyle: { backgroundColor: '#D4F580', color: '#253723', fontSize: 9 } }} />
        <Tab.Screen name="My listings" component={ListingsScreen} />
        <Tab.Screen name="Account" component={AccountScreen} />
      </Tab.Navigator>}
    </View>
  </View>
  <Sheet visible={sheet === 'location'} title="Where’s your next drive?" subtitle="Set your home base for your car-buying journey." onClose={() => setSheet('')} footer={<Button title="Save location" icon="location-outline" disabled={!customLocation.trim()} onPress={() => { setLocation(customLocation.trim()); setSheet(''); notify('Your home location has been updated.'); }} />}><Field label="City or ZIP code" value={customLocation} onChangeText={setCustomLocation} placeholder="e.g. San Francisco, CA" /><Txt style={{ fontFamily: fonts.semibold, marginTop: 24, marginBottom: 12, fontSize: 12 }}>Popular locations</Txt><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{['San Francisco, CA', 'Los Angeles, CA', 'New York, NY', 'Austin, TX'].map(city => <Chip key={city} label={city} active={city === customLocation} onPress={() => setCustomLocation(city)} />)}</View><Txt style={{ fontSize: 11, lineHeight: 18, color: theme.muted, marginTop: 20 }}>Our demo collection features Bay Area cars. Your location is saved for future searches; all demo listings remain visible.</Txt></Sheet>
  <Sheet visible={sheet === 'notifications'} title="Your pit stop" subtitle="A few things you might want to know." onClose={() => setSheet('')}><View style={{ gap: 14 }}><Pressable onPress={() => { setSheet(''); go('Messages'); }} style={{ padding: 17, backgroundColor: theme.tint, borderRadius: 12, flexDirection: 'row', gap: 13 }}><Icon name="chatbubble-ellipses-outline" color={theme.forest} /><View style={{ flex: 1 }}><Txt style={{ fontFamily: fonts.semibold, fontSize: 13 }}>{unread ? 'You have a new conversation' : 'Keep the conversation going'}</Txt><Txt style={{ color: theme.muted, fontSize: 12, marginTop: 5, lineHeight: 19 }}>Your messages are one tap away.</Txt></View><Icon name="chevron-forward" size={15} /></Pressable><View style={{ padding: 17, backgroundColor: theme.soft, borderRadius: 12, flexDirection: 'row', gap: 13 }}><Icon name="sparkles-outline" /><View style={{ flex: 1 }}><Txt style={{ fontFamily: fonts.semibold, fontSize: 13 }}>Welcome to a better way to buy.</Txt><Txt style={{ color: theme.muted, fontSize: 12, marginTop: 5, lineHeight: 19 }}>Explore the collection, save your favorites, and find a car that feels like you.</Txt></View></View></View></Sheet>
  <Sheet visible={sheet === 'help'} title="Every good drive has support." subtitle="How can we help you along the way?" onClose={() => setSheet('')} footer={<Button title="Save support request" disabled={!support.trim()} icon="checkmark" onPress={async () => { const storage = (await import('@react-native-async-storage/async-storage')).default; try { await storage.setItem('drivn-support', JSON.stringify({ text: support, date: new Date().toISOString() })); setSupport(''); setSheet(''); notify('Support request saved on this device.'); } catch { notify('Could not save your request. Please try again.'); } }} />}><Field label="Your message" value={support} onChangeText={setSupport} multiline placeholder="Tell us what’s on your mind…" /><View style={{ marginTop: 20, backgroundColor: theme.soft, borderRadius: 10, padding: 15 }}><Txt style={{ fontSize: 12, color: theme.muted, lineHeight: 20 }}>You’re exploring the Drivn demo. Messages, listings, and support requests are stored on your device, not sent to real sellers or a support team. Never share payment or sensitive personal information here.</Txt></View></Sheet>
  </SafeAreaView>;
}
