import React from 'react';
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, TextInput, View, ViewStyle, KeyboardAvoidingView, Platform, ScrollView } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { useApp } from '../lib/store';

export const fonts = { regular: 'DMRegular', medium: 'DMMedium', semibold: 'DMSemibold', bold: 'DMBold' };
export function Txt({ children, style, ...props }: any) { const { theme } = useApp(); return <Text {...props} style={[{ fontFamily: fonts.regular, color: theme.text, fontSize: 14 }, style]}>{children}</Text>; }
export function Icon({ name, size = 20, color, style }: { name: any; size?: number; color?: string; style?: any }) { const { theme } = useApp(); return <Ionicons name={name} size={size} color={color || theme.text} style={style} />; }
export function Button({ title, onPress, icon, variant = 'primary', style, disabled, loading }: { title: string; onPress: () => void; icon?: any; variant?: 'primary' | 'dark' | 'outline' | 'soft'; style?: ViewStyle; disabled?: boolean; loading?: boolean }) {
  const { theme, darkMode } = useApp();
  const bg = variant === 'primary' ? theme.green : variant === 'dark' ? '#243C30' : variant === 'soft' ? theme.soft : 'transparent';
  const color = variant === 'dark' ? '#fff' : variant === 'primary' ? '#23371C' : theme.text;
  return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled || loading} onPress={onPress} style={({ pressed, hovered }: any) => [{ backgroundColor: bg, borderRadius: 10, paddingHorizontal: 20, minHeight: 48, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 10, borderWidth: variant === 'outline' ? 1 : 0, borderColor: theme.border, opacity: disabled ? .45 : pressed ? .75 : 1, transform: [{ translateY: hovered ? -1 : 0 }] }, style]}>{loading ? <ActivityIndicator color={color} /> : <><Txt style={{ fontFamily: fonts.bold, fontSize: 13, color }}>{title}</Txt>{icon && <Icon name={icon} size={18} color={color} />}</>}</Pressable>;
}
export function IconButton({ name, onPress, style, size = 20, color, label }: { name: any; onPress: () => void; style?: ViewStyle; size?: number; color?: string; label?: string }) { const { theme } = useApp(); return <Pressable accessibilityRole="button" accessibilityLabel={label || name} onPress={onPress} style={({ pressed }) => [{ width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.surface, opacity: pressed ? .6 : 1 }, style]}><Icon name={name} size={size} color={color} /></Pressable>; }
export function Chip({ label, active, onPress, icon, count }: { label: string; active?: boolean; onPress: () => void; icon?: any; count?: number }) { const { theme } = useApp(); return <Pressable onPress={onPress} accessibilityRole="button" style={({ hovered, pressed }: any) => ({ flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 16, height: 40, borderRadius: 9, borderWidth: 1, borderColor: active ? '#283D31' : theme.border, backgroundColor: active ? '#283D31' : hovered ? theme.soft : theme.surface, opacity: pressed ? .7 : 1 })}>{icon && <Icon name={icon} size={17} color={active ? '#D4F580' : theme.muted} />}<Txt style={{ fontFamily: fonts.medium, fontSize: 12, color: active ? '#fff' : theme.text }}>{label}</Txt>{count !== undefined && <View style={{ backgroundColor: active ? '#4C5E47' : theme.soft, borderRadius: 4, paddingHorizontal: 5, paddingVertical: 1 }}><Txt style={{ fontSize: 10, color: active ? '#DCF6A7' : theme.muted }}>{count}</Txt></View>}</Pressable>; }
export function Field({ label, value, onChangeText, placeholder, keyboardType, multiline, style, ...props }: any) { const { theme } = useApp(); return <View style={[{ gap: 8 }, style]}><Txt style={{ fontSize: 12, fontFamily: fonts.semibold }}>{label}</Txt><TextInput accessibilityLabel={label} {...props} value={value} onChangeText={onChangeText} placeholder={placeholder} keyboardType={keyboardType || 'default'} placeholderTextColor={theme.subtle} multiline={multiline} returnKeyType={multiline ? 'default' : 'done'} style={{ fontFamily: fonts.regular, fontSize: 14, color: theme.text, backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 13, minHeight: multiline ? 110 : 47, textAlignVertical: multiline ? 'top' : 'center', outlineStyle: 'none' } as any} /></View>; }
export function Sheet({ visible, title, subtitle, onClose, children, footer, wide = false }: { visible: boolean; title: string; subtitle?: string; onClose: () => void; children: React.ReactNode; footer?: React.ReactNode; wide?: boolean }) { const { theme } = useApp(); return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={{ flex: 1, backgroundColor: '#101F19A6', justifyContent: 'center', alignItems: 'center', padding: 20 }}><Pressable accessibilityLabel="Close dialog" onPress={onClose} style={StyleSheet.absoluteFill} /><View style={{ backgroundColor: theme.surface, borderRadius: 20, width: '100%', maxWidth: wide ? 660 : 500, maxHeight: '90%', overflow: 'hidden', shadowColor: '#000', shadowOpacity: .15, shadowRadius: 30, elevation: 20 }}><View style={{ padding: 24, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: theme.border }}><View style={{ flex: 1 }}><Txt style={{ fontSize: 23, fontFamily: fonts.bold }}>{title}</Txt>{subtitle && <Txt style={{ color: theme.muted, fontSize: 12, marginTop: 5, lineHeight: 19 }}>{subtitle}</Txt>}</View><IconButton name="close" onPress={onClose} style={{ backgroundColor: theme.soft }} /></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: 24 }} showsVerticalScrollIndicator={false}>{children}</ScrollView>{footer && <View style={{ padding: 20, borderTopWidth: 1, borderTopColor: theme.border }}>{footer}</View>}</View></KeyboardAvoidingView></Modal>; }
export function EmptyState({ icon = 'search-outline', title, description, action, onAction }: { icon?: any; title: string; description: string; action?: string; onAction?: () => void }) { const { theme } = useApp(); return <View style={{ alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24, paddingVertical: 65, gap: 14 }}><View style={{ width: 72, height: 72, borderRadius: 24, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.tint, marginBottom: 7 }}><Icon name={icon} size={30} color={theme.forest} /></View><Txt style={{ fontSize: 22, fontFamily: fonts.bold, textAlign: 'center' }}>{title}</Txt><Txt style={{ color: theme.muted, textAlign: 'center', lineHeight: 22, maxWidth: 360 }}>{description}</Txt>{action && onAction && <Button title={action} onPress={onAction} style={{ marginTop: 10 }} icon="arrow-forward" />}</View>; }
export function PageHeading({ eyebrow, title, subtitle, action }: any) { const { theme } = useApp(); return <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 16, marginBottom: 28 }}><View style={{ flex: 1 }}>{eyebrow && <Txt style={{ fontSize: 10, letterSpacing: 1.7, fontFamily: fonts.bold, color: theme.muted, marginBottom: 8 }}>{eyebrow}</Txt>}<Txt style={{ fontSize: 31, letterSpacing: -1, fontFamily: fonts.bold }}>{title}</Txt>{subtitle && <Txt style={{ color: theme.muted, marginTop: 8, fontSize: 13, lineHeight: 21 }}>{subtitle}</Txt>}</View>{action}</View>; }
export function BackHeader({ title, navigation, right }: any) { const { theme } = useApp(); return <View style={{ borderBottomWidth: 1, borderBottomColor: theme.border, backgroundColor: theme.surface }}><View style={{ width: '100%', maxWidth: 1160, alignSelf: 'center', paddingHorizontal: 24, height: 74, flexDirection: 'row', alignItems: 'center', gap: 14 }}><IconButton name="arrow-back" onPress={() => navigation.goBack()} style={{ backgroundColor: theme.soft }} label="Go back" /><Txt style={{ fontFamily: fonts.semibold, fontSize: 16, flex: 1 }}>{title}</Txt>{right}</View></View>; }
