import React, { useState } from 'react';
import { FlatList, Pressable, Switch, View, useWindowDimensions } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useApp } from '../lib/store';
import { Button, Chip, Field, fonts, Icon, PageHeading, Sheet, Txt } from '../components/UI';
export default function AccountScreen({ navigation }: any) {
  const { theme, darkMode, name, setName, email, setEmail, location, saved, ownCars, appearance, setAppearance, notify } = useApp(); const { width } = useWindowDimensions();
  const [sheet, setSheet] = useState(''); const [editName, setEditName] = useState(name); const [editEmail, setEditEmail] = useState(email);
  const initials = name.split(' ').slice(0, 2).map(x => x[0]).join('');
  return <View style={{ flex: 1, backgroundColor: theme.bg }}><FlatList data={['profile', 'preferences', 'about']} keyExtractor={x => x} contentContainerStyle={{ padding: width < 650 ? 20 : 32, maxWidth: 1050, width: '100%', alignSelf: 'center', gap: 22, paddingBottom: 40 }} showsVerticalScrollIndicator={false} ListHeaderComponent={<PageHeading eyebrow="YOUR PERSONAL PIT STOP" title="Make yourself at home." subtitle="Your details, your preferences, your next chapter." />} renderItem={({ item }) => {
    if (item === 'profile') return <View style={{ backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 16, padding: width < 650 ? 21 : 30 }}><View style={{ flexDirection: 'row', gap: 17, alignItems: 'center' }}><View style={{ width: 65, height: 65, borderRadius: 24, backgroundColor: '#EDE9DC', justifyContent: 'center', alignItems: 'center' }}><Txt style={{ fontSize: 21, fontFamily: fonts.semibold, color: '#7A7053' }}>{initials}</Txt></View><View style={{ flex: 1 }}><Txt style={{ fontSize: 23, fontFamily: fonts.bold }}>{name}</Txt><Txt style={{ color: theme.muted, fontSize: 12, marginTop: 5 }}>{email}</Txt></View><Pressable accessibilityLabel="Edit profile" onPress={() => { setEditName(name); setEditEmail(email); setSheet('edit'); }} style={{ width: 38, height: 38, borderRadius: 10, backgroundColor: theme.soft, justifyContent: 'center', alignItems: 'center' }}><Icon name="create-outline" size={18} /></Pressable></View><View style={{ flexDirection: 'row', gap: 5, alignItems: 'center', marginTop: 23 }}><Icon name="location-outline" size={14} color={theme.muted} /><Txt style={{ color: theme.muted, fontSize: 12 }}>{location}</Txt><Txt style={{ marginLeft: 'auto', fontSize: 10, color: theme.muted }}>A member of the Drivn demo</Txt></View><View style={{ flexDirection: 'row', gap: 15, marginTop: 25, paddingTop: 23, borderTopWidth: 1, borderColor: theme.border }}>{[[saved.length, 'Saved cars', 'Saved cars'], [ownCars.length, 'Active listings', 'My listings']].map(([value, label, screen]) => <Pressable key={label} onPress={() => navigation.navigate(screen)} style={{ flex: 1, gap: 6 }}><Txt style={{ fontFamily: fonts.bold, fontSize: 27 }}>{value}</Txt><View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><Txt style={{ color: theme.muted, fontSize: 11 }}>{label}</Txt><Icon name="arrow-forward" size={12} color={theme.muted} /></View></Pressable>)}</View></View>;
    if (item === 'preferences') return <View style={{ backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 16, padding: 25 }}><Txt style={{ fontSize: 18, fontFamily: fonts.bold }}>Just your style.</Txt><Txt style={{ color: theme.muted, fontSize: 12, marginTop: 6 }}>A little personalization makes all the difference.</Txt><View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 18, marginTop: 27 }}><View style={{ flexDirection: 'row', gap: 12, alignItems: 'center' }}><Icon name="color-palette-outline" size={21} color={theme.muted} /><View><Txt style={{ fontFamily: fonts.semibold, fontSize: 13 }}>Appearance</Txt><Txt style={{ color: theme.muted, fontSize: 10, marginTop: 4 }}>Set the mood for your next search.</Txt></View></View><View style={{ flexDirection: 'row', gap: 7 }}>{['light', 'dark', 'system'].map(a => <Chip key={a} label={a[0].toUpperCase() + a.slice(1)} active={appearance === a} onPress={() => setAppearance(a)} icon={a === 'light' ? 'sunny-outline' : a === 'dark' ? 'moon-outline' : 'phone-portrait-outline'} />)}</View></View></View>;
    return <View style={{ backgroundColor: '#213A2D', borderRadius: 16, padding: 28, gap: 13 }}><Icon name="sparkles-outline" color="#D4F580" size={23} /><Txt style={{ fontFamily: fonts.bold, color: '#fff', fontSize: 23, letterSpacing: -.5 }}>Less friction. More freedom.</Txt><Txt style={{ color: '#BFCABB', fontSize: 12, lineHeight: 21, maxWidth: 640 }}>We believe buying a car should feel like the beginning of something good. Drivn brings thoughtful design and a more personal touch to your next great drive.</Txt><Pressable onPress={() => setSheet('privacy')} style={{ flexDirection: 'row', gap: 7, alignItems: 'center', marginTop: 7 }}><Txt style={{ fontSize: 11, fontFamily: fonts.semibold, color: '#D4F580' }}>Your data, your peace of mind</Txt><Icon name="arrow-forward" size={14} color="#D4F580" /></Pressable><Txt style={{ color: '#8DA08B', fontSize: 9, marginTop: 10 }}>DRIVN DEMO · MADE FOR YOUR NEXT CHAPTER · 2026</Txt></View>;
  }} />
  <Sheet visible={sheet === 'edit'} title="The person behind the wheel." subtitle="Keep your personal details up to date." onClose={() => setSheet('')} footer={<Button title="Save changes" icon="checkmark" disabled={!editName.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(editEmail)} onPress={() => { setName(editName.trim()); setEmail(editEmail.trim()); setSheet(''); notify('Your profile has been updated.'); }} />}><View style={{ gap: 20 }}><Field label="Full name" value={editName} onChangeText={setEditName} placeholder="Your name" textContentType="name" /><Field label="Email address" value={editEmail} onChangeText={setEditEmail} placeholder="you@example.com" keyboardType="email-address" autoCapitalize="none" textContentType="emailAddress" /><Txt style={{ color: theme.muted, fontSize: 11, lineHeight: 19 }}>These details are stored only on this device. You don’t need a real email address to explore the demo.</Txt></View></Sheet>
  <Sheet visible={sheet === 'privacy'} title="Your data stays in your lane." subtitle="A straightforward note about this demo." onClose={() => setSheet('')}><View style={{ gap: 20 }}>{[['Stored on your device', 'Your profile, favorites, conversations, and listings are saved locally in your browser or app storage. They aren’t shared with sellers or a remote marketplace.'], ['No real transactions', 'All featured cars, prices, seller details, and sample conversations are illustrative. Payment calculations are estimates, not lending offers. Test drives are not booked with real sellers.'], ['You’re in control', 'You can remove saved cars, delete your listings, and edit your profile at any time. Clearing this app’s browser or device storage removes all your locally saved data.']].map(([title, text]) => <View key={title}><Txt style={{ fontFamily: fonts.bold, fontSize: 14, marginBottom: 7 }}>{title}</Txt><Txt style={{ color: theme.muted, fontSize: 12, lineHeight: 21 }}>{text}</Txt></View>)}</View></Sheet>
  </View>;
}
