import React, { useState } from 'react';
import { FlatList, Modal, Platform, Pressable, Share, View, useWindowDimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Image } from 'expo-image';
import { useApp } from '../lib/store';
import { money, miles, monthly } from '../lib/data';
import { BackHeader, Button, Chip, EmptyState, Field, fonts, Icon, IconButton, Sheet, Txt } from '../components/UI';
import CarCard from '../components/CarCard';

export default function CarDetailScreen({ route, navigation }: any) {
  const { theme, inventory, saved, toggleSaved, startConversation, notify } = useApp();
  const { width } = useWindowDimensions(); const wide = width >= 900;
  const car = inventory.find(c => c.id === route.params.carId);
  const [sheet, setSheet] = useState(''); const [expanded, setExpanded] = useState(false);
  const [down, setDown] = useState(car ? String(Math.round(car.price * .2)) : '0');
  const [term, setTerm] = useState(72); const [apr, setApr] = useState('6.5');
  const [date, setDate] = useState(''); const [time, setTime] = useState('');
  if (!car) return <SafeAreaView style={{ flex: 1, backgroundColor: theme.bg }}><BackHeader title="Car details" navigation={navigation} /><EmptyState icon="car-outline" title="This car has moved on." description="The listing is no longer available. Your next great drive is still out there." action="Back to exploring" onAction={() => navigation.goBack()} /></SafeAreaView>;
  const amount = Math.max(0, car.price - (Number(down) || 0));
  const rate = (Number(apr) || 0) / 1200;
  const payment = rate ? (amount * rate) / (1 - Math.pow(1 + rate, -term)) : amount / term;
  const validFinance = Number(down) >= 0 && Number(down) <= car.price && Number(apr) >= 0 && Number(apr) <= 50;
  const openChat = (text?: string) => { const id = startConversation(car, text); setSheet(''); navigation.navigate('Chat', { conversationId: id }); };
  const share = async () => { const message = `I found a great car on Drivn: ${car.year} ${car.make} ${car.model} — ${money(car.price)}, ${miles(car.mileage)}, ${car.location}. Demo listing.`; try { if (Platform.OS === 'web' && typeof navigator !== 'undefined' && navigator.clipboard) { await navigator.clipboard.writeText(message); notify('Car details copied. Share the good drive.'); } else { await Share.share({ message }); } } catch { notify('Sharing isn’t available right now. Please try again.'); } };
  const dates = Array.from({ length: 5 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() + i + 1); return { short: d.toLocaleDateString('en-US', { weekday: 'short', day: 'numeric' }), full: d.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }) }; });
  return <SafeAreaView edges={['top', 'bottom']} style={{ flex: 1, backgroundColor: theme.bg }}>
    <BackHeader title="A closer look" navigation={navigation} right={<View style={{ flexDirection: 'row', gap: 8 }}><IconButton name="share-outline" onPress={share} label="Share car" style={{ backgroundColor: theme.soft }} /><IconButton name={saved.includes(car.id) ? 'heart' : 'heart-outline'} onPress={() => toggleSaved(car.id)} label="Save car" color={theme.forest} style={{ backgroundColor: theme.soft }} /></View>} />
    <FlatList data={['overview', 'story', 'related']} keyExtractor={x => x} showsVerticalScrollIndicator={false} contentContainerStyle={{ padding: width < 650 ? 20 : 32, width: '100%', maxWidth: 1200, alignSelf: 'center', paddingBottom: 40 }} renderItem={({ item }) => {
      if (item === 'overview') return <View style={{ flexDirection: wide ? 'row' : 'column', gap: 24 }}>
        <View style={{ flex: wide ? 1.65 : undefined }}>
          <Pressable onPress={() => setSheet('gallery')} style={{ aspectRatio: 1.45, borderRadius: 17, overflow: 'hidden', backgroundColor: theme.soft }}><Image source={car.image} style={{ width: '100%', height: '100%' }} contentFit="cover" transition={Platform.OS === 'web' ? 0 : 250} loading="eager" priority="high" accessibilityLabel={`${car.make} ${car.model} listing photo`} /><View style={{ position: 'absolute', top: 18, left: 18, backgroundColor: '#FFFFFFEE', borderRadius: 7, paddingVertical: 8, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 5 }}><Icon name="car-sport-outline" color="#586F40" size={14} /><Txt style={{ fontSize: 10, fontFamily: fonts.semibold, color: '#3D5131' }}>{car.own ? 'Your listing' : 'Pre-owned · Demo listing'}</Txt></View><View style={{ position: 'absolute', bottom: 17, right: 17, backgroundColor: '#192D24BC', borderRadius: 7, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 7 }}><Icon name="expand-outline" color="#fff" size={15} /><Txt style={{ fontSize: 10, color: '#fff' }}>View photo</Txt></View></Pressable>
          <View style={{ flexDirection: 'row', marginTop: 15, gap: 10 }}>{[['Mileage', miles(car.mileage), 'speedometer-outline'], ['Fuel', car.fuel, 'flash-outline'], ['Gearbox', car.transmission, 'git-compare-outline'], ['Body style', car.type, 'car-sport-outline']].map(([label, value, icon]) => <View key={label} style={{ flex: 1, borderWidth: 1, borderColor: theme.border, backgroundColor: theme.surface, borderRadius: 10, padding: width < 500 ? 10 : 16, gap: 8 }}><Icon name={icon} size={19} color={theme.muted} /><Txt style={{ fontSize: 9, color: theme.muted }}>{label}</Txt><Txt numberOfLines={1} style={{ fontSize: width < 500 ? 10 : 12, fontFamily: fonts.semibold }}>{value}</Txt></View>)}</View>
        </View>
        <View style={{ flex: wide ? 1 : undefined, borderWidth: 1, borderColor: theme.border, backgroundColor: theme.surface, borderRadius: 20, padding: 28, alignSelf: wide ? 'flex-start' : 'stretch', shadowColor: '#213C30', shadowOffset: { width: 0, height: 7 }, shadowOpacity: .05, shadowRadius: 22 }}>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 12 }}><Txt style={{ fontSize: 10, letterSpacing: 1.5, color: theme.muted, fontFamily: fonts.semibold }}>{car.year} · {car.make.toUpperCase()}</Txt>{car.badge && <View style={{ paddingVertical: 4, paddingHorizontal: 7, backgroundColor: theme.tint, borderRadius: 5, marginLeft: 'auto' }}><Txt style={{ fontSize: 9, color: theme.forest }}>{car.badge}</Txt></View>}</View>
          <Txt style={{ fontSize: 32, lineHeight: 38, fontFamily: fonts.bold, letterSpacing: -1.1 }}>{car.make}{'\n'}{car.model}</Txt><View style={{ flexDirection: 'row', gap: 5, alignItems: 'center', marginTop: 13 }}><Icon name="location-outline" size={13} color={theme.muted} /><Txt style={{ color: theme.muted, fontSize: 11 }}>{car.location}</Txt></View>
          <View style={{ marginVertical: 24, paddingVertical: 22, borderTopWidth: 1, borderBottomWidth: 1, borderColor: theme.border }}><Txt style={{ color: theme.muted, fontSize: 10, marginBottom: 7, letterSpacing: 1.4, fontFamily: fonts.medium }}>ASKING PRICE</Txt><Txt style={{ fontSize: 36, fontFamily: fonts.bold, letterSpacing: -1 }}>{money(car.price)}</Txt><Pressable onPress={() => setSheet('finance')} style={{ flexDirection: 'row', gap: 6, alignItems: 'center', marginTop: 7 }}><Txt style={{ color: theme.muted, fontSize: 11 }}>Est. {money(monthly(car.price))}/mo</Txt><Icon name="information-circle-outline" color={theme.muted} size={13} /><Txt style={{ fontSize: 11, fontFamily: fonts.semibold, color: theme.forest, marginLeft: 'auto' }}>Calculate</Txt></Pressable><Txt style={{ fontSize: 10, color: theme.muted, lineHeight: 17, marginTop: 13 }}>20% down · 72 months · Sample 6.5% APR</Txt><Txt style={{ fontSize: 10, color: theme.subtle, lineHeight: 17 }}>Taxes, registration, and other fees not included.</Txt></View>
          {car.own ? <View style={{ gap: 10 }}><Button title="Manage your listing" icon="arrow-forward" onPress={() => navigation.popTo('Main', { screen: 'My listings' })} /><Txt style={{ fontSize: 11, color: theme.muted, textAlign: 'center', lineHeight: 18 }}>This listing is live in your local demo marketplace.</Txt></View> : <View style={{ gap: 11 }}><Button title="Message the seller" icon="chatbubble-ellipses-outline" onPress={() => openChat()} /><Button title="Arrange a test drive" icon="calendar-outline" onPress={() => setSheet('drive')} variant="outline" /><Txt style={{ fontSize: 9, color: theme.muted, textAlign: 'center', lineHeight: 17, marginTop: 4 }}>No pressure. Just the start of a good conversation.</Txt></View>}
        </View>
      </View>;
      if (item === 'story') return <View style={{ flexDirection: wide ? 'row' : 'column', gap: 24, marginTop: 30 }}>
        <View style={{ flex: 1.65 }}><Txt style={{ fontFamily: fonts.bold, fontSize: 22, letterSpacing: -.5 }}>A car with a story.</Txt><Txt style={{ color: theme.muted, fontSize: 13, lineHeight: 23, marginTop: 13 }}>{car.description}</Txt>
          <Pressable onPress={() => setExpanded(v => !v)} style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderColor: theme.border, paddingVertical: 20, marginTop: 23 }}><Txt style={{ fontFamily: fonts.semibold, fontSize: 14 }}>The finer details</Txt><Icon name={expanded ? 'remove' : 'add'} size={18} /></Pressable>
          {expanded && <View style={{ backgroundColor: theme.surface, borderRadius: 12, padding: 20, gap: 15 }}>{[['Exterior color', car.color], ['Model year', String(car.year)], ['Transmission', car.transmission], ['Power', car.horsepower ? `${car.horsepower} hp` : 'Not specified'], ['Listing reference', car.id.toUpperCase()]].map(([label, value]) => <View key={label} style={{ flexDirection: 'row', justifyContent: 'space-between', gap: 20 }}><Txt style={{ color: theme.muted, fontSize: 12 }}>{label}</Txt><Txt style={{ fontFamily: fonts.medium, fontSize: 12, flexShrink: 1 }}>{value}</Txt></View>)}</View>}
          <View style={{ backgroundColor: theme.tint, borderRadius: 12, padding: 19, flexDirection: 'row', gap: 13, marginTop: 6 }}><Icon name="shield-checkmark-outline" size={22} color={theme.forest} /><View style={{ flex: 1 }}><Txt style={{ fontFamily: fonts.semibold, fontSize: 12 }}>Confidence comes standard.</Txt><Txt style={{ color: theme.muted, fontSize: 11, lineHeight: 19, marginTop: 5 }}>Always inspect a car in person, verify its history, and meet in a safe public place before making a payment. Drivn never asks for a deposit to view a car.</Txt></View></View>
        </View>
        <View style={{ flex: 1, alignSelf: wide ? 'flex-start' : 'stretch', backgroundColor: theme.surface, borderRadius: 14, padding: 24, borderWidth: 1, borderColor: theme.border }}><Txt style={{ fontSize: 10, color: theme.muted, letterSpacing: 1.3, fontFamily: fonts.semibold }}>MEET THE SELLER</Txt><View style={{ flexDirection: 'row', gap: 13, alignItems: 'center', marginTop: 18 }}><View style={{ width: 45, height: 45, borderRadius: 13, backgroundColor: theme.soft, alignItems: 'center', justifyContent: 'center' }}><Icon name={car.own ? 'person-outline' : 'business-outline'} size={22} color={theme.forest} /></View><View style={{ flex: 1 }}><Txt style={{ fontFamily: fonts.bold, fontSize: 13 }}>{car.seller}</Txt><Txt style={{ color: theme.muted, fontSize: 10, marginTop: 4 }}>{car.location}</Txt></View></View><View style={{ height: 1, backgroundColor: theme.border, marginVertical: 18 }} /><View style={{ flexDirection: 'row', gap: 7, alignItems: 'center' }}><Icon name={car.own || car.seller === 'Alex Chen' ? 'person-outline' : 'storefront-outline'} color={theme.forest} size={15} /><Txt style={{ fontSize: 11, color: theme.muted }}>{car.own ? 'Your local demo listing' : car.seller === 'Alex Chen' ? 'Private seller · Demo profile' : 'Independent dealer · Demo profile'}</Txt></View><Txt style={{ fontSize: 10, color: theme.subtle, lineHeight: 18, marginTop: 15 }}>This is an illustrative listing. Prices, specifications, and seller details are sample data, not a live offer. Messages and viewing requests stay on your device.</Txt></View>
      </View>;
      return <View style={{ marginTop: 35, paddingTop: 29, borderTopWidth: 1, borderColor: theme.border }}><Txt style={{ fontSize: 23, fontFamily: fonts.bold, letterSpacing: -.5, marginBottom: 20 }}>A few more you might love.</Txt><FlatList horizontal data={inventory.filter(c => c.id !== car.id).slice(0, 4)} keyExtractor={c => c.id} showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 17, paddingBottom: 8 }} renderItem={({ item, index }) => <View style={{ width: width < 650 ? 280 : 335 }}><CarCard car={item} index={index} onPress={() => navigation.push('CarDetail', { carId: item.id })} /></View>} /></View>;
    }} />
    <Sheet visible={sheet === 'finance'} title="Make the numbers work for you." subtitle="An estimate to help you plan. Not a financing offer." onClose={() => setSheet('')}><View style={{ backgroundColor: theme.tint, borderRadius: 13, padding: 25, alignItems: 'center', marginBottom: 25 }}><Txt style={{ color: theme.muted, fontSize: 11 }}>Estimated monthly payment</Txt><Txt style={{ fontSize: 44, fontFamily: fonts.bold, marginTop: 4 }}>{validFinance ? money(payment) : '—'}<Txt style={{ fontSize: 15, color: theme.muted }}>/mo</Txt></Txt></View><View style={{ gap: 19 }}><Field label="Down payment ($)" value={down} onChangeText={(v: string) => setDown(v.replace(/[^0-9]/g, ''))} keyboardType="numeric" /><Field label="Annual percentage rate (%)" value={apr} onChangeText={setApr} keyboardType="decimal-pad" /><View><Txt style={{ fontFamily: fonts.semibold, fontSize: 12, marginBottom: 10 }}>Loan term</Txt><View style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap' }}>{[36, 48, 60, 72, 84].map(n => <Chip key={n} label={`${n} mo`} active={term === n} onPress={() => setTerm(n)} />)}</View></View>{!validFinance && <Txt style={{ color: '#AC6757', fontSize: 12 }}>Use a down payment between $0 and {money(car.price)}, and an APR between 0% and 50%.</Txt>}<Txt style={{ color: theme.muted, fontSize: 10, lineHeight: 18 }}>Illustrative calculation only. The default 6.5% APR is a sample assumption, not a current rate. Excludes taxes, title, registration, and other fees. Actual rates and eligibility depend on your lender.</Txt></View></Sheet>
    <Sheet visible={sheet === 'drive'} title="Some things are better in person." subtitle={`Arrange a viewing of the ${car.make} ${car.model}.`} onClose={() => setSheet('')} footer={<Button title="Save test-drive request" icon="calendar-outline" disabled={!date || !time} onPress={() => { openChat(`Hi! I’d love to arrange a test drive of the ${car.year} ${car.make} ${car.model} on ${date} at ${time}. Please let me know if that works for you.`); notify('Request saved to your demo conversation. Not a confirmed booking.'); }} />}><Txt style={{ fontFamily: fonts.semibold, marginBottom: 13 }}>Pick your day</Txt><View style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap' }}>{dates.map(d => <Chip key={d.full} label={d.short} active={date === d.full} onPress={() => setDate(d.full)} />)}</View><Txt style={{ fontFamily: fonts.semibold, marginTop: 26, marginBottom: 13 }}>And a time that suits you</Txt><View style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap' }}>{['9:00 AM', '10:30 AM', '12:00 PM', '2:00 PM', '3:30 PM', '5:00 PM'].map(t => <Chip key={t} label={t} active={time === t} onPress={() => setTime(t)} />)}</View><Txt style={{ color: theme.muted, fontSize: 11, lineHeight: 19, marginTop: 22 }}>This demo request is saved to your conversation on this device. It isn’t sent to a seller and does not reserve a test drive.</Txt></Sheet>
    <Modal visible={sheet === 'gallery'} transparent animationType="fade" onRequestClose={() => setSheet('')}><SafeAreaView style={{ flex: 1, backgroundColor: '#111B17F5', justifyContent: 'center' }}><View style={{ position: 'absolute', top: 30, right: 24, zIndex: 2 }}><IconButton name="close" onPress={() => setSheet('')} color="#fff" style={{ backgroundColor: '#FFFFFF20' }} label="Close photo" /></View><Image source={car.image} style={{ width: '100%', height: '75%' }} contentFit="contain" /><Txt style={{ color: '#fff', textAlign: 'center', marginTop: 15, fontFamily: fonts.medium }}>{car.year} {car.make} {car.model}</Txt><Txt style={{ color: '#B1B9B2', textAlign: 'center', marginTop: 7, fontSize: 11 }}>1 of 1 · {car.own ? 'Listing photo' : 'Illustrative photo'}</Txt></SafeAreaView></Modal>
  </SafeAreaView>;
}
