import React, { useMemo, useState } from 'react';
import { FlatList, Platform, Pressable, TextInput, View, useWindowDimensions, ScrollView, RefreshControl } from 'react-native';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { useApp } from '../lib/store';
import { cars, categories, defaultFilters, Filters, money } from '../lib/data';
import { Button, Chip, EmptyState, Field, fonts, Icon, IconButton, Sheet, Txt } from '../components/UI';
import CarCard from '../components/CarCard';

const collection = [cars[1], cars[0], cars[5]];
const collectionText = [ ['Find a car that', 'feels like you.', 'Exceptional cars. A better way to buy.'], ['A little less ordinary.', 'A lot more drive.', 'For the roads you haven’t taken. Yet.'], ['More room for', 'your next adventure.', 'Your everyday escape starts here.'] ];
export default function DiscoverScreen({ navigation }: any) {
  const { theme, inventory, location, notify } = useApp();
  const [heroError, setHeroError] = useState(false);
  const { width } = useWindowDimensions();
  const desktop = width >= 1000; const compact = width < 650;
  const cols = width > 1230 ? 3 : width > 730 ? 2 : 1;
  const [category, setCategory] = useState('All cars');
  const [draft, setDraft] = useState<Filters>({ ...defaultFilters });
  const [filters, setFilters] = useState<Filters>({ ...defaultFilters });
  const [sheet, setSheet] = useState('');
  const [sort, setSort] = useState('Recommended');
  const [slide, setSlide] = useState(0);
  const [refreshing, setRefreshing] = useState(false);
  const [collectionOnly, setCollectionOnly] = useState(false);
  const results = useMemo(() => {
    let list = inventory.filter(c => {
      const text = `${c.year} ${c.make} ${c.model} ${c.fuel} ${c.type}`.toLowerCase();
      return (!filters.query || text.includes(filters.query.toLowerCase().trim())) && (filters.make === 'All' || c.make === filters.make) && (!filters.min || c.price >= Number(filters.min)) && (!filters.max || c.price <= Number(filters.max)) && (filters.type === 'All' || c.type === filters.type) && (filters.fuel === 'All' || c.fuel === filters.fuel) && (category === 'All cars' || (category === 'Electric' ? c.fuel === 'Electric' : c.type === category)) && (!collectionOnly || c.featured);
    });
    if (sort === 'Price: low to high') list.sort((a, b) => a.price - b.price);
    if (sort === 'Price: high to low') list.sort((a, b) => b.price - a.price);
    if (sort === 'Lowest mileage') list.sort((a, b) => a.mileage - b.mileage);
    if (sort === 'Newest year') list.sort((a, b) => b.year - a.year);
    return list;
  }, [inventory, filters, category, sort, collectionOnly]);
  const apply = () => { if (draft.min && draft.max && Number(draft.min) > Number(draft.max)) { notify('Minimum price must be less than maximum price.'); return; } setFilters({ ...draft }); setSheet(''); };
  const reset = () => { setDraft({ ...defaultFilters }); setFilters({ ...defaultFilters }); setCategory('All cars'); setCollectionOnly(false); };
  const filterCount = [filters.make !== 'All', filters.type !== 'All', filters.fuel !== 'All', !!filters.min, !!filters.max].filter(Boolean).length;
  const refresh = () => { setRefreshing(true); setTimeout(() => { setRefreshing(false); notify('You’re all caught up. Happy car hunting!'); }, 650); };
  const header = <View>
    <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 }}><View style={{ flex: 1 }}><Txt style={{ fontSize: compact ? 27 : 30, fontFamily: fonts.bold, letterSpacing: -.9 }}>Good things are just a drive away.</Txt><Txt style={{ color: theme.muted, fontSize: 12, marginTop: 8, lineHeight: 20 }}>Find your next car. Fall in love with the journey.</Txt></View>{desktop && <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6, paddingTop: 10 }}><Icon name="location-outline" size={13} color={theme.muted} /><Txt style={{ color: theme.muted, fontSize: 11 }}>Discover the Bay Area</Txt></View>}</View>
    <View style={{ height: compact ? 340 : 282, borderRadius: 20, overflow: 'hidden', backgroundColor: '#152A20', shadowColor: '#152A20', shadowOpacity: .12, shadowRadius: 24, shadowOffset: { width: 0, height: 8 } }}>
      <Image source={collection[slide].image} accessibilityLabel="Featured car photograph" contentFit="cover" contentPosition={compact ? { top: '50%', left: '72%' } : { top: '58%', left: '50%' }} transition={Platform.OS === 'web' ? 0 : 350} loading="eager" priority="high" onError={() => setHeroError(true)} onLoad={() => setHeroError(false)} style={{ position: 'absolute', right: 0, top: 0, width: compact ? '100%' : '72%', height: '100%' }} />
      {heroError && <View style={{ position: 'absolute', right: 35, top: 45, opacity: .13 }}><Icon name="car-sport-outline" size={155} color="#D4F580" /></View>}
      <LinearGradient colors={compact ? ['#12251EEF', '#12251E8A', '#12251E55', '#12251EF0'] : ['#152A20', '#152A20FA', '#152A20BD', '#152A2020', '#152A2000']} locations={compact ? [0, .38, .67, 1] : [0, .23, .39, .63, 1]} start={{ x: 0, y: 0 }} end={{ x: compact ? .12 : 1, y: compact ? 1 : 0 }} style={{ position: 'absolute', inset: 0 }} />
      <View style={{ padding: compact ? 25 : 34, paddingBottom: compact ? 86 : 40, paddingLeft: compact ? 25 : 36, height: '100%', justifyContent: compact ? 'flex-start' : 'center', alignItems: 'flex-start' }}>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 16 }}><View style={{ width: 5, height: 5, borderRadius: 3, backgroundColor: '#D4F580' }} /><Txt style={{ color: '#D4F580', fontSize: 9, letterSpacing: 2.3, fontFamily: fonts.semibold }}>THE DRIVN EDIT</Txt></View>
        <Txt style={{ color: '#fff', fontSize: compact ? 35 : 43, lineHeight: compact ? 40 : 47, letterSpacing: -1.7, fontFamily: fonts.bold }}>{collectionText[slide][0]}{'\n'}<Txt style={{ color: '#D4F580', fontSize: compact ? 35 : 43, lineHeight: compact ? 40 : 47, letterSpacing: -1.7, fontFamily: fonts.bold }}>{collectionText[slide][1]}</Txt></Txt>
        <Txt style={{ color: '#D0D9CB', fontSize: 12, marginTop: 11 }}>{collectionText[slide][2]}</Txt>
        <Button title="Explore the collection" icon="arrow-forward" onPress={() => { setCollectionOnly(v => !v); setCategory('All cars'); setFilters({ ...defaultFilters }); setDraft({ ...defaultFilters }); }} style={{ minHeight: 42, paddingHorizontal: 17, borderRadius: 9, marginTop: 20 }} />
      </View>
      {!compact && <View style={{ position: 'absolute', top: 23, right: 23, borderWidth: 1, borderColor: '#FFFFFF45', borderRadius: 6, paddingHorizontal: 10, paddingVertical: 7, backgroundColor: '#172B2370' }}><Txt style={{ fontSize: 9, letterSpacing: 1.4, color: '#fff', fontFamily: fonts.medium }}>CURATED, NOT CROWDED.</Txt></View>}
      <Pressable accessibilityRole="button" accessibilityLabel="View featured car" onPress={() => navigation.navigate('CarDetail', { carId: collection[slide].id })} style={{ position: 'absolute', right: compact ? undefined : 24, left: compact ? 25 : undefined, bottom: compact ? 22 : 65, flexDirection: 'row', alignItems: 'center', gap: 13, backgroundColor: '#15291EC4', borderWidth: 1, borderColor: '#FFFFFF28', paddingVertical: 10, paddingHorizontal: 13, borderRadius: 10, maxWidth: compact ? '66%' : undefined }}><View style={{ gap: 4, flexShrink: 1 }}><Txt numberOfLines={1} style={{ color: '#fff', fontSize: 11, fontFamily: fonts.semibold }}>{collection[slide].year} {collection[slide].make} {collection[slide].model}</Txt><Txt style={{ color: '#D8EDB5', fontSize: 10 }}>{money(collection[slide].price)} · Explore this car</Txt></View><Icon name="arrow-forward" color="#D4F580" size={16} /></Pressable>
      <View style={{ position: 'absolute', bottom: compact ? 24 : 28, right: compact ? 17 : 24, flexDirection: 'row', alignItems: 'center', gap: compact ? 5 : 10 }}><IconButton name="chevron-back" onPress={() => setSlide((slide + 2) % 3)} size={14} style={{ backgroundColor: '#FFFFFF20', borderWidth: 1, borderColor: '#FFFFFF30', width: 27, height: 27 }} color="#fff" label="Previous featured car" /><Txt style={{ color: '#fff', fontSize: 10, fontFamily: fonts.medium }}>0{slide + 1}<Txt style={{ color: '#D9DFDA99', fontSize: 10 }}> / 03</Txt></Txt><IconButton name="chevron-forward" onPress={() => setSlide((slide + 1) % 3)} size={14} style={{ backgroundColor: '#FFFFFF20', borderWidth: 1, borderColor: '#FFFFFF30', width: 27, height: 27 }} color="#fff" label="Next featured car" /></View>
    </View>
    <View style={{ backgroundColor: theme.surface, borderRadius: 14, padding: 16, borderWidth: 1, borderColor: theme.border, marginTop: compact ? 16 : -18, marginHorizontal: compact ? 0 : 22, zIndex: 2, flexDirection: compact ? 'column' : 'row', alignItems: compact ? 'stretch' : 'center', gap: compact ? 16 : 0, shadowColor: '#223923', shadowOpacity: .08, shadowRadius: 22, shadowOffset: { width: 0, height: 6 } }}>
      <View style={{ flex: compact ? undefined : 1.3, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 7 }}><Icon name="search-outline" size={19} color={theme.muted} /><View style={{ flex: 1 }}><Txt style={{ fontSize: 9, color: theme.muted, marginBottom: 4 }}>YOUR NEXT CAR</Txt><TextInput value={draft.query} onChangeText={query => setDraft({ ...draft, query })} onSubmitEditing={apply} returnKeyType="search" placeholder="Search make, model, or keyword" placeholderTextColor={theme.subtle} style={{ fontFamily: fonts.medium, fontSize: 12, paddingVertical: 4, paddingHorizontal: 0, color: theme.text, outlineStyle: 'none', width: '100%' } as any} /></View></View>
      <View style={{ flex: compact ? undefined : 1.6, flexDirection: 'row', alignItems: 'center' }}>
        <Pressable onPress={() => setSheet('make')} style={{ flex: 1, paddingHorizontal: compact ? 6 : 23, borderLeftWidth: compact ? 0 : 1, borderColor: theme.border, gap: 8 }}><Txt style={{ fontSize: 9, color: theme.muted }}>MAKE & MODEL</Txt><View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><Txt numberOfLines={1} style={{ fontSize: 11, fontFamily: fonts.medium }}>{draft.make === 'All' ? 'All makes' : draft.make}</Txt><Icon name="chevron-down" size={12} color={theme.muted} /></View></Pressable>
        <Pressable onPress={() => setSheet('budget')} style={{ flex: 1, paddingHorizontal: 20, borderLeftWidth: 1, borderColor: theme.border, gap: 8 }}><Txt style={{ fontSize: 9, color: theme.muted }}>PRICE RANGE</Txt><View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><Txt style={{ fontSize: 11, fontFamily: fonts.medium }}>{draft.max ? `Under $${Number(draft.max).toLocaleString()}` : 'Any price'}</Txt><Icon name="chevron-down" size={12} color={theme.muted} /></View></Pressable>
      </View><Button title="Search cars" icon="search-outline" onPress={apply} style={{ minHeight: 44, paddingHorizontal: 21, borderRadius: 8 }} />
    </View>
    <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 13, marginBottom: 7 }}><View style={{ flexDirection: 'row', gap: 6, alignItems: 'center' }}><Icon name="shield-checkmark-outline" size={13} color={theme.muted} /><Txt style={{ fontSize: 10, color: theme.muted }}>A better way to buy. Every step of the way.</Txt></View>{!compact && <View style={{ flexDirection: 'row', gap: 16 }}>{['Dealer & private listings', 'Side-by-side comparison', 'No listing fees'].map(t => <View key={t} style={{ flexDirection: 'row', gap: 4, alignItems: 'center' }}><Icon name="checkmark" size={12} color="#77985D" /><Txt style={{ fontSize: 9, color: theme.muted }}>{t}</Txt></View>)}</View>}</View>
    <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 17, gap: 10 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><Txt style={{ fontFamily: fonts.bold, fontSize: 22, letterSpacing: -.6 }}>{collectionOnly ? 'The Drivn collection' : 'Discover your next car'}</Txt>{!compact && <View style={{ backgroundColor: theme.soft, borderRadius: 5, paddingHorizontal: 7, paddingVertical: 4 }}><Txt style={{ fontSize: 10, color: theme.muted }}>{results.length} cars</Txt></View>}</View><Pressable onPress={() => setSheet('sort')} style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}><Txt style={{ color: theme.muted, fontSize: 10 }}>{compact ? 'Sort' : 'Sort by:'}</Txt>{!compact && <Txt style={{ fontFamily: fonts.medium, fontSize: 10 }}>{sort}</Txt>}<Icon name="chevron-down" size={12} /></Pressable></View>
    <View style={{ flexDirection: 'row', gap: 10, marginBottom: 20, alignItems: 'center' }}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingRight: 8 }} style={{ flex: 1 }}>{categories.map((c, i) => <Chip key={c} label={c === 'SUV' ? 'SUVs' : c === 'Sedan' ? 'Sedans' : c === 'Coupe' ? 'Coupes' : c} active={category === c} onPress={() => setCategory(c)} icon={['grid-outline', 'car-sport-outline', 'car-outline', 'speedometer-outline', 'flash-outline'][i]} count={i === 0 ? inventory.length : undefined} />)}</ScrollView><Pressable onPress={() => { setDraft({ ...filters }); setSheet('filters'); }} style={{ flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 8, height: 40, paddingHorizontal: 13 }}><Icon name="options-outline" size={17} /><Txt style={{ fontSize: 11, fontFamily: fonts.medium }}>Filters{filterCount ? ` (${filterCount})` : ''}</Txt></Pressable></View>
    {(filters.query || filterCount > 0 || collectionOnly) && <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}><Txt style={{ color: theme.muted, fontSize: 12 }}>{results.length} matches{filters.query ? ` for “${filters.query}”` : ''}{collectionOnly ? ' in our curated collection' : ''}</Txt><Pressable onPress={reset}><Txt style={{ color: theme.forest, fontSize: 12, fontFamily: fonts.semibold }}>Clear all</Txt></Pressable></View>}
  </View>;
  return <View style={{ flex: 1, backgroundColor: theme.bg }}><FlatList key={cols} data={results} numColumns={cols} keyExtractor={c => c.id} ListHeaderComponent={header} renderItem={({ item, index }) => <View style={{ flex: 1 / cols, paddingHorizontal: cols > 1 ? 8 : 0, marginBottom: 19 }}><CarCard car={item} index={index} onPress={() => navigation.navigate('CarDetail', { carId: item.id })} /></View>} columnWrapperStyle={cols > 1 ? { marginHorizontal: -8 } : undefined} contentContainerStyle={{ width: '100%', maxWidth: 1380, alignSelf: 'center', paddingHorizontal: compact ? 20 : 32, paddingTop: 25, paddingBottom: 25 }} showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={theme.forest} />} ListEmptyComponent={<EmptyState title="The right car is out there." description="Try a different make or a wider price range. Your next great drive might surprise you." action="Reset filters" onAction={reset} />} ListFooterComponent={<View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12, marginTop: 16, paddingTop: 22, borderTopWidth: 1, borderColor: theme.border }}><Txt style={{ fontSize: 10, color: theme.muted }}>A little less searching. A lot more driving.</Txt><Txt style={{ fontSize: 9, color: theme.subtle }}>Demo marketplace · Illustrative listings & prices</Txt></View>} />
    <Sheet visible={sheet === 'make'} title="A make for every journey" subtitle="Choose your favorite, or keep your options open." onClose={() => setSheet('')}><View style={{ gap: 8 }}>{['All', ...Array.from(new Set(inventory.map(c => c.make)))].map(make => <Pressable key={make} onPress={() => { setDraft({ ...draft, make }); setSheet(''); }} style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 15, borderRadius: 9, backgroundColor: draft.make === make ? theme.tint : theme.soft }}><Txt style={{ fontFamily: fonts.medium }}>{make === 'All' ? 'All makes' : make}</Txt>{draft.make === make && <Icon name="checkmark-circle" color={theme.forest} />}</Pressable>)}</View></Sheet>
    <Sheet visible={sheet === 'budget' || sheet === 'filters'} title={sheet === 'budget' ? 'Find your comfort zone' : 'Make it your kind of car'} subtitle="A few details to help find your perfect match." onClose={() => setSheet('')} footer={<View style={{ flexDirection: 'row', gap: 12 }}><Button title="Reset" onPress={() => setDraft({ ...defaultFilters })} variant="outline" style={{ flex: 1 }} /><Button title="Show matches" onPress={apply} icon="arrow-forward" style={{ flex: 2 }} /></View>}>
      <Txt style={{ fontFamily: fonts.semibold, marginBottom: 14 }}>Price range</Txt><View style={{ flexDirection: 'row', gap: 12 }}><Field label="Minimum price ($)" value={draft.min} onChangeText={(min: string) => setDraft({ ...draft, min: min.replace(/[^0-9]/g, '') })} placeholder="0" keyboardType="numeric" style={{ flex: 1 }} /><Field label="Maximum price ($)" value={draft.max} onChangeText={(max: string) => setDraft({ ...draft, max: max.replace(/[^0-9]/g, '') })} placeholder="No limit" keyboardType="numeric" style={{ flex: 1 }} /></View>
      <View style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginTop: 14 }}>{['40000', '60000', '80000', '100000'].map(p => <Chip key={p} label={`Under $${Number(p) / 1000}k`} active={draft.max === p} onPress={() => setDraft({ ...draft, max: p })} />)}</View>
      {sheet === 'filters' && <>{[['Body style', 'type', ['All', 'SUV', 'Sedan', 'Coupe']], ['Fuel type', 'fuel', ['All', 'Gasoline', 'Electric', 'Hybrid']], ['Make', 'make', ['All', ...Array.from(new Set(inventory.map(c => c.make)))]]].map(([label, key, items]: any) => <View key={key} style={{ marginTop: 28 }}><Txt style={{ fontFamily: fonts.semibold, marginBottom: 12 }}>{label}</Txt><View style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap' }}>{items.map((v: string) => <Chip key={v} label={v} active={(draft as any)[key] === v} onPress={() => setDraft({ ...draft, [key]: v })} />)}</View></View>)}</>}
    </Sheet>
    <Sheet visible={sheet === 'sort'} title="A fresh perspective" subtitle="Choose how you’d like to see your matches." onClose={() => setSheet('')}><View style={{ gap: 8 }}>{['Recommended', 'Price: low to high', 'Price: high to low', 'Lowest mileage', 'Newest year'].map(s => <Pressable key={s} onPress={() => { setSort(s); setSheet(''); }} style={{ flexDirection: 'row', padding: 16, alignItems: 'center', justifyContent: 'space-between', borderRadius: 10, backgroundColor: sort === s ? theme.tint : theme.soft }}><Txt>{s}</Txt>{sort === s && <Icon name="checkmark" color={theme.forest} />}</Pressable>)}</View></Sheet>
  </View>;
}
