import React, { useState } from 'react';
import { FlatList, KeyboardAvoidingView, Platform, Pressable, View, useWindowDimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Image } from 'expo-image';
import * as ImagePicker from 'expo-image-picker';
import { useApp } from '../lib/store';
import { cars, Car, money } from '../lib/data';
import { BackHeader, Button, Chip, EmptyState, Field, fonts, Icon, PageHeading, Sheet, Txt } from '../components/UI';

export default function SellCarScreen({ navigation, route }: any) {
  const { theme, name, location, addCar, updateCar, ownCars } = useApp(); const { width } = useWindowDimensions(); const wide = width > 800;
  const editing = !!route.params?.carId;
  const existing = ownCars.find(car => car.id === route.params?.carId);
  const [step, setStep] = useState(0); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [success, setSuccess] = useState(false);
  const [form, setForm] = useState({ make: existing?.make ?? '', model: existing?.model ?? '', year: String(existing?.year ?? 2023), mileage: existing ? String(existing.mileage) : '', type: existing?.type ?? 'Sedan', fuel: existing?.fuel ?? 'Gasoline', transmission: existing?.transmission ?? 'Automatic', color: existing?.color ?? '', description: existing?.description ?? '', price: existing ? String(existing.price) : '', seller: existing?.seller ?? name, location: existing?.location ?? location });
  const [image, setImage] = useState<any>(existing?.image ?? null); const [photoId, setPhotoId] = useState('');
  if (editing && !existing) return <SafeAreaView edges={['top', 'bottom']} style={{ flex: 1, backgroundColor: theme.bg }}><BackHeader title="Edit your listing" navigation={navigation} /><EmptyState icon="car-outline" title="This listing is no longer available." description="Only your own active listings can be edited." action="Back to my listings" onAction={() => navigation.popTo('Main', { screen: 'My listings' })} /></SafeAreaView>;
  const update = (key: string, value: string) => { setForm(p => ({ ...p, [key]: value })); setError(''); };
  const pickImage = async () => {
    try {
      if (Platform.OS !== 'web') { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { setError('Photo access is needed to upload. You can also choose a demo photo below.'); return; } }
      const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [16, 10], quality: .6, base64: true });
      if (!result.canceled && result.assets[0]) { const asset = result.assets[0]; if (!asset.base64) { setError('This photo could not be saved. Try another image.'); return; } if (asset.base64.length > 4000000) { setError('Please choose a smaller photo (under 3 MB).'); return; } setImage({ uri: `data:${asset.mimeType || 'image/jpeg'};base64,${asset.base64}` }); setPhotoId('upload'); setError(''); }
    } catch { setError('We couldn’t open your photos. Try again or choose a demo photo.'); }
  };
  const next = () => {
    if (step === 0) {
      if (!form.make.trim() || !form.model.trim()) { setError('Tell us the make and model of your car.'); return; }
      if (!/^\d{4}$/.test(form.year) || Number(form.year) < 1900 || Number(form.year) > 2027) { setError('Enter a model year between 1900 and 2027.'); return; }
      if (form.mileage === '' || Number(form.mileage) < 0 || Number(form.mileage) > 999999) { setError('Enter a mileage between 0 and 999,999 miles.'); return; }
    }
    if (step === 1) {
      if (!image) { setError('Add a photo or choose one from the demo collection.'); return; }
      if (form.description.trim().length < 30) { setError('Tell your car’s story in at least 30 characters.'); return; }
      if (!form.color.trim()) { setError('What color is your car?'); return; }
    }
    setError(''); setStep(s => s + 1);
  };
  const publish = () => {
    if (!form.price || Number(form.price) < 100 || Number(form.price) > 10000000) { setError('Set an asking price between $100 and $10,000,000.'); return; }
    if (!form.seller.trim() || !form.location.trim()) { setError('Add a seller name and location to finish your listing.'); return; }
    setBusy(true);
    const car: Car = { ...existing, id: existing?.id ?? `your-car-${Date.now()}`, make: form.make.trim(), model: form.model.trim(), year: Number(form.year), mileage: Number(form.mileage), price: Number(form.price), type: form.type as Car['type'], fuel: form.fuel as Car['fuel'], transmission: form.transmission, color: form.color.trim(), description: form.description.trim(), image, seller: form.seller.trim(), location: form.location.trim(), horsepower: existing?.horsepower ?? 0, own: true };
    setTimeout(() => { if (editing) updateCar(car); else addCar(car); setBusy(false); setSuccess(true); }, 500);
  };
  const blocks = step === 0 ? ['identity', 'specs'] : step === 1 ? ['photo', 'story'] : ['preview', 'price'];
  return <SafeAreaView edges={['top', 'bottom']} style={{ flex: 1, backgroundColor: theme.bg }}><BackHeader title={editing ? 'Edit your listing' : 'Pass on the good miles'} navigation={navigation} /><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
    <FlatList data={blocks} keyExtractor={x => x} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={{ padding: width < 650 ? 20 : 32, width: '100%', maxWidth: 850, alignSelf: 'center', paddingBottom: 25 }} ListHeaderComponent={<><PageHeading eyebrow="YOUR CAR’S NEXT CHAPTER" title={(editing ? ['Fine-tune your listing.', 'Refresh your car’s story.', 'A final look at your updates.'] : ['First, let’s meet your car.', 'Give it a little personality.', 'The last stop before you’re live.'])[step]} subtitle={['A few details help the right buyer find you.', 'A great photo and a good story make all the difference.', 'Set a fair price. Make a great first impression.'][step]} /><View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 27 }}>{['The essentials', 'Photo & story', 'Price & publish'].map((label, i) => <React.Fragment key={label}>{i > 0 && <View style={{ flex: 1, height: 1, backgroundColor: i <= step ? '#8CA96C' : theme.border, marginHorizontal: width < 500 ? 7 : 16 }} />}<Pressable disabled={i >= step} onPress={() => { setStep(i); setError(''); }} style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><View style={{ width: 27, height: 27, borderRadius: 9, backgroundColor: i <= step ? '#2E4734' : theme.soft, alignItems: 'center', justifyContent: 'center' }}>{i < step ? <Icon name="checkmark" size={14} color="#D4F580" /> : <Txt style={{ fontSize: 10, fontFamily: fonts.bold, color: i === step ? '#D4F580' : theme.muted }}>0{i + 1}</Txt>}</View>{(width > 500 || step === i) && <Txt style={{ fontSize: 10, fontFamily: fonts.semibold, color: i <= step ? theme.text : theme.muted }}>{label}</Txt>}</Pressable></React.Fragment>)}</View></>} renderItem={({ item }) => {
      if (item === 'identity') return <View style={{ backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 14, padding: 24, marginBottom: 20 }}><Txt style={{ fontFamily: fonts.bold, fontSize: 17, marginBottom: 21 }}>The introduction</Txt><View style={{ flexDirection: width < 500 ? 'column' : 'row', gap: 17 }}><Field style={{ flex: 1 }} label="Make" value={form.make} onChangeText={(v: string) => update('make', v)} placeholder="e.g. BMW" /><Field style={{ flex: 1 }} label="Model" value={form.model} onChangeText={(v: string) => update('model', v)} placeholder="e.g. M4 Competition" /></View><View style={{ flexDirection: 'row', gap: 17, marginTop: 21 }}><Field style={{ flex: 1 }} label="Model year" value={form.year} onChangeText={(v: string) => update('year', v.replace(/[^0-9]/g, '').slice(0, 4))} keyboardType="numeric" /><Field style={{ flex: 1 }} label="Mileage (mi)" value={form.mileage} onChangeText={(v: string) => update('mileage', v.replace(/[^0-9]/g, ''))} placeholder="e.g. 12500" keyboardType="numeric" /></View></View>;
      if (item === 'specs') return <View style={{ backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 14, padding: 24, gap: 23 }}>{[['Body style', 'type', ['Sedan', 'SUV', 'Coupe']], ['Fuel type', 'fuel', ['Gasoline', 'Electric', 'Hybrid']], ['Transmission', 'transmission', ['Automatic', 'Manual']]].map(([label, key, options]: any) => <View key={key}><Txt style={{ fontFamily: fonts.semibold, fontSize: 12, marginBottom: 12 }}>{label}</Txt><View style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap' }}>{options.map((o: string) => <Chip key={o} label={o} active={(form as any)[key] === o} onPress={() => update(key, o)} />)}</View></View>)}</View>;
      if (item === 'photo') return <View style={{ backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 14, padding: 24, marginBottom: 20 }}><Txt style={{ fontFamily: fonts.bold, fontSize: 17, marginBottom: 17 }}>A great first impression</Txt><Pressable onPress={pickImage} style={{ height: image ? 260 : 165, borderRadius: 12, borderWidth: image ? 0 : 1, borderStyle: 'dashed', borderColor: '#B3C19E', backgroundColor: theme.soft, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', gap: 10 }}>{image ? <><Image source={image} style={{ width: '100%', height: '100%' }} contentFit="cover" /><View style={{ position: 'absolute', bottom: 12, right: 12, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 7, backgroundColor: '#FFFFFFE8' }}><Icon name="camera-outline" size={15} color="#30462B" /><Txt style={{ fontSize: 10, color: '#30462B', fontFamily: fonts.semibold }}>Change photo</Txt></View></> : <><Icon name="cloud-upload-outline" size={28} color={theme.forest} /><Txt style={{ fontFamily: fonts.semibold, fontSize: 13 }}>Upload your car’s best angle</Txt><Txt style={{ color: theme.muted, fontSize: 10 }}>JPG or PNG · Under 3 MB recommended</Txt></>}</Pressable><Txt style={{ fontSize: 11, fontFamily: fonts.medium, color: theme.muted, marginTop: 19, marginBottom: 12 }}>Just exploring? Choose a demo photo.</Txt><FlatList horizontal data={cars} keyExtractor={c => c.id} showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 10 }} renderItem={({ item: c }) => <Pressable accessibilityLabel={`Choose ${c.make} photo`} onPress={() => { setImage(c.image); setPhotoId(c.id); setError(''); }} style={{ width: 100, height: 65, borderRadius: 8, borderWidth: 2, borderColor: photoId === c.id ? '#809F56' : 'transparent', padding: 2 }}><Image source={c.image} contentFit="cover" style={{ width: '100%', height: '100%', borderRadius: 5 }} />{photoId === c.id && <View style={{ position: 'absolute', top: 5, right: 5 }}><Icon name="checkmark-circle" size={17} color="#D4F580" /></View>}</Pressable>} /></View>;
      if (item === 'story') return <View style={{ backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 14, padding: 24, gap: 20 }}><Field label="Exterior color" value={form.color} onChangeText={(v: string) => update('color', v)} placeholder="e.g. Alpine White" /><Field label="Tell your car’s story" value={form.description} onChangeText={(v: string) => update('description', v)} multiline placeholder="What makes your car special? Mention its condition, favorite features, and service history." /><Txt style={{ fontSize: 10, color: theme.muted, alignSelf: 'flex-end', marginTop: -12 }}>{form.description.length} characters · 30 minimum</Txt></View>;
      if (item === 'preview') return <View style={{ borderWidth: 1, borderColor: theme.border, backgroundColor: theme.surface, borderRadius: 14, overflow: 'hidden', flexDirection: width < 550 ? 'column' : 'row', marginBottom: 20 }}><Image source={image} style={{ width: width < 550 ? '100%' : 235, height: 170 }} contentFit="cover" /><View style={{ padding: 23, justifyContent: 'center', gap: 7, flex: 1 }}><Txt style={{ fontSize: 9, color: theme.muted, letterSpacing: 1.5 }}>LOOKING GOOD</Txt><Txt style={{ fontSize: 21, fontFamily: fonts.bold }}>{form.year} {form.make} {form.model}</Txt><Txt style={{ fontSize: 11, color: theme.muted }}>{Number(form.mileage).toLocaleString()} mi · {form.fuel} · {form.transmission}</Txt><Txt style={{ fontSize: 11, color: theme.muted }}>{form.color}</Txt></View></View>;
      return <View style={{ borderWidth: 1, borderColor: theme.border, backgroundColor: theme.surface, borderRadius: 14, padding: 24, gap: 23 }}><Field label="Your asking price ($)" value={form.price} onChangeText={(v: string) => update('price', v.replace(/[^0-9]/g, ''))} placeholder="e.g. 42500" keyboardType="numeric" /><View style={{ flexDirection: wide ? 'row' : 'column', gap: 18 }}><Field style={{ flex: 1 }} label="Seller name" value={form.seller} onChangeText={(v: string) => update('seller', v)} placeholder="Your name or dealership" /><Field style={{ flex: 1 }} label="Car location" value={form.location} onChangeText={(v: string) => update('location', v)} placeholder="City, State" /></View><View style={{ backgroundColor: theme.tint, borderRadius: 10, padding: 17, flexDirection: 'row', gap: 12 }}><Icon name="information-circle-outline" size={20} color={theme.forest} /><Txt style={{ flex: 1, color: theme.muted, fontSize: 11, lineHeight: 20 }}>{editing ? 'Your updates will replace the existing listing on this device, keeping the same listing and saved favorites. Changes are not posted to a public marketplace.' : 'Your listing will be published in your demo marketplace on this device. It isn’t posted to a public marketplace. No payment or personal contact information is required.'}</Txt></View></View>;
    }} ListFooterComponent={<View style={{ marginTop: 22 }}>{!!error && <View style={{ padding: 15, backgroundColor: '#F9EAE3', borderRadius: 10, marginBottom: 15, flexDirection: 'row', gap: 9 }}><Icon name="alert-circle-outline" size={18} color="#A45840" /><Txt style={{ color: '#A45840', fontSize: 12, lineHeight: 19, flex: 1 }}>{error}</Txt></View>}<View style={{ flexDirection: 'row', gap: 12 }}><Button title={step === 0 ? 'Cancel' : 'Go back'} variant="outline" onPress={() => { if (step === 0) navigation.goBack(); else { setStep(s => s - 1); setError(''); } }} style={{ flex: 1 }} /><Button title={step === 2 ? (editing ? 'Save listing changes' : 'Publish my listing') : 'Keep going'} icon={step === 2 ? 'checkmark' : 'arrow-forward'} onPress={step === 2 ? publish : next} loading={busy} style={{ flex: 2 }} /></View><Txt style={{ textAlign: 'center', color: theme.subtle, fontSize: 10, marginTop: 17 }}>No listing fees. No pressure. Just possibilities.</Txt></View>} />
  </KeyboardAvoidingView><Sheet visible={success} title={editing ? 'Looking good. All up to date.' : 'Here’s to the next chapter.'} subtitle={editing ? 'Your listing has been updated on this device. Your saved favorites are still connected.' : 'Your car is looking good. Your listing is now live on this device.'} onClose={() => { setSuccess(false); navigation.popTo('Main', { screen: 'My listings' }); }} footer={<Button title="See my listing" icon="arrow-forward" onPress={() => { setSuccess(false); navigation.popTo('Main', { screen: 'My listings' }); }} />}><View style={{ alignItems: 'center', gap: 17, paddingVertical: 15 }}><View style={{ width: 72, height: 72, borderRadius: 25, backgroundColor: theme.tint, alignItems: 'center', justifyContent: 'center' }}><Icon name="checkmark" size={36} color={theme.forest} /></View><Txt style={{ fontSize: 23, fontFamily: fonts.bold }}>{form.make} {form.model}</Txt><Txt style={{ color: theme.muted }}>{money(Number(form.price))} · {form.location}</Txt></View></Sheet></SafeAreaView>;
}
